### PR TITLE
Fixed streaming server connection error not getting propagated.

### LINKED ISSUE #22: When given clientID is duplicated, it complains on subject, not on clientID.
When given `clientID` is duplicated, it does not fail on connect, but on subscribe. Traceback is
```
Error: Subject must be supplied
    at Object.<anonymous> (/app/node_modules/nats/lib/nats.js:70:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/node_modules/nats/index.js:1:80)
    at Module._compile (module.js:556:32)
```

### PR DESCRIPTION
**Pull request by aricart**
[FIX #22] Added error checking on stan connection.
[CHANGED] Bumped version

### CODE REVIEW

File: test/basics.js [hunk 1]
```diff
@@ -127,6 +127,27 @@ describe('Basics', function () {
...
   });
 
+  it('duplicate client id should fire error', function (done) {
+    var wantTwo = 2;
+    var id = nuid.next();
+    var stan = STAN.connect(cluster, id, PORT);
+    stan.on('connect', function () {
+      var stan2 = STAN.connect(cluster, id, PORT);
+      stan2.on('error', function() {
+        wantTwo--;
```
Comment (ColinSullivan1) [inline test/basics.js]: Should you check for "duplicate" in the reason here?

**Comment by ColinSullivan1** [comment]
LGTM.

**Comment by kozlovic** [comment]
LGTM
